config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about'

  get 'pages/documents'

  get 'pages/circuits'


  get 'pages/join'

  get 'pages/structures'

  get 'pages/software'

  get 'pages/business'


	root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

 def about
 end

 def documents
 end

 def circuits
 end


 def join
	 render layout: 'join'
 end


 def structures
 end

 def software
 end

 def business
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_bootstrap.html.erb
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<script src="https://use.fontawesome.com/0467ea9c44.js"></script>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
   	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
			<script
			  src="https://code.jquery.com/jquery-3.2.1.min.js"
				  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
					  crossorigin="anonymous"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to image_tag("nav-logo.png", alt: 'MAAV', class: "top"), root_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	</ul>
	<ul class="navbar-nav navbar-right">
		<li><%= link_to "Home", root_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "About", about_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "Circuits", pages_circuits_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "Software", pages_documents_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "Structures", pages_structures_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "Business", pages_business_path, class: "nav-item nav-link"%></li>
		<li><%= link_to "Join Us", pages_join_path, class: "nav-item nav-link"%></li>
	</ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maav</title>
    <%= csrf_meta_tags %>
		<%= favicon_link_tag 'nav-logo.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/bootstrap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/join.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag  "main" %>
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
		<%= render 'layouts/bootstrap' %>

		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/smoothscroll.js"></script>


	</head>

	<body data-spy="scroll" data-offset="0" data-target="#navigation">
		<%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
    <header class="masthead">
      <div class="overlay">
        <div class="container">
        	<br>
        	<br>
          <h1 class="display-1 text-white">About Us</h1>
          <br>
          <br>
        </div>
      </div>
    </header>
    <div id="slide-2">
    <section>
      <div class="container" >
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <%= image_tag "about/historia.jpg", class: "img-fluid rounded-circle" %>
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">A brief history...</h2>
              <p>MAAV was formed in a tiny room in 2008 by a group of four students at the University of Michigan.
                 We were one of the very first teams in Michigan’s history to work with autonomous vehicles, and we
                 revolutionized the Wilson Centre, the building where the organization is located, by accommodating
                 the increase in popularity of software engineering. Fun fact: the four original founders went on to
                 form their own startup, a drone corporation known as Sky Specs.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="p-5">
              <%= image_tag "about/1iarc.jpeg", class: "img-fluid rounded-circle" %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="p-5">
              <h2 class="display-4">IARC</h2>
              <p>MAAV participates in the International Aerial Robotics Competition (IARC), held in the United States
                 and China biannually, against teams from across the world. The competition consists of several missions,
                 or challenges, that teams must complete to win. These vary from search and rescue missions to flying
                 into a village 3km away, searching for a particular building, and inserting a robot into an open
                 window in that building. No team has successfully completed all the challenges in the competition’s
                 history, but MAAV's drone consistently ranks highly. In 2012, it won first place in the
                 competition for successfully maneuvering and mapping the set course in one of the challenges.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <%= image_tag "about/joinus.jpeg", class: "img-fluid rounded-circle" %>
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">Join us!</h2>
              <p>Joining MAAV is as simple as joining the mailing list and going to workdays and meetings. All our
                 subteam meetings during the week are announced on the mailing list, and every weekend, we dedicate
                 several hours of work in the Wilson Center.  Please note that our mailing list is relatively high-
                 volume, as all of our version control systems, our continuous integration setup, and other team
               communications are sent to this list. Email us at maav-leads@umich.edu! </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Michigan Autonomous Aerial Vehicles</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/pages/business.html.erb
<header class="masthead business">
  <div class="overlay">
    <div class="container">
	    <br>
	    <br>
      <h1 class="display-1 text-white">Business</h1>
      <br>
      <br>
    </div>
  </div>
</header>
<div id="business-slide-2">
<section>
  <div class="container" >
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "business/website.jpg", class: "img-fluid rounded-circle", style: "height: 25rem;"%>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Website</h2>
	  <p> The business team handles all of MAAVs web projects including this website!
	 The site is made using HTML (Bootstrap) and CSS on the front end, and uses
	Ruby on Rails as the backend. We are always looking for people interested in web dev to help make our site the best at IARC.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
	<div class="p-5">
	  <%= image_tag "business/sponsorship.jpg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6">
	<div class="p-5">
	  <h2 class="display-4">Sponsorship</h2>
	  <p>In order for anything we do to be possible, we require funding from all of our generous
	  sponsors. The sponsorship department of the business subteam is responsible for reaching
	out to our current sponsors and ensuring their continued support. The business team also works to form new relationships with interested sponsors.
	 MAAV thanks all its sponsors greatly for their contributions over the years.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "business/blog.jpg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Blog</h2>
	  <p>Our blog on Medium is a great way to keep up with everything that MAAV does.
	  It is meant as a resource both for members of MAAV to understand what the other
	subteams are doing, and for non-members to understand what the club is doing. It will
      be updated approximately every month, with a post detailing all the activites of each of the
	individual subteams, to give people a good idea of our big-picture workings.</p>
	</div>
      </div>
    </div>
  </div>
</section>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Michigan Autonomous Aerial Vehicles</p>
  </div>
  <!-- /.container -->
</footer>

app/views/pages/circuits.html.erb
<header class="masthead circuits">
  <div class="overlay">
    <div class="container">
	    <br>
	    <br>
      <h1 class="display-1 text-white">Circuits</h1>
      <br>
      <br>
    </div>
  </div>
</header>
<div id="circuits-slide-2">
<section>
  <div class="container" >
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
    <%= image_tag "circuits/circuits_solder.jpeg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Bringing The Drone to Life</h2>
	  <p> MAAV builds all of the electrical components in house.
	  The circuits team leads and design and construction of these components.
	  The team works with the different sensors on the quad-copter and routes information
	  across the vehicle to the electrical components. We also design a PCB to power the quad-copter.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
	<div class="p-5">
	  <%= image_tag "circuits/boards.png", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6">
	<div class="p-5">
	  <h2 class="display-4">Design and Safety</h2>
	  <p>Circuits works to find the the best solution and modern technology that we can use to
		  create a fast and powerful signal board and power board. The vehicle's printed circuit board (PCB)
		  has to provide a platform for control software to run and communicate with navigation software,
		  as well as manage the safety of the battery, motors, and operators.
		  Circuits tools such as Eagle and Subversion for design and collboration.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "circuits/meeting.jpg", class: "img-fluid rounded-circle", style: "height: 25rem;"%>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Highly Collaborative</h2>
	  <p>Comprised mainly of CE and EE majors, the circuits team is close knit and highly agile.
	In order to develop a robust system, the circuits team collaborates heavily with the
	  structures and software infrastructure teams.</p>
	</div>
      </div>
    </div>
  </div>
</section>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Michigan Autonomous Aerial Vehicles</p>
  </div>
  <!-- /.container -->
</footer>

app/views/pages/documents.html.erb
<header class="masthead software">
  <div class="overlay">
    <div class="container">
	    <br>
	    <br>
      <h1 class="display-1 text-white">Software</h1>
      <br>
      <br>
    </div>
  </div>
</header>
<div id="software-slide-2">
<section>
  <div class="container" >
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "circuits/wunderboy.jpg", class: "img-fluid rounded-circle", style: "height: 25rem;"%>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">The Brains of the Operation</h2>
	  <p>Members of software work in groups to tackle computer vision and localization challenges, and develop a strategy to complete our mission in the IARC.
		  To do this, we work closely with graduate students and leverage advanced algorithms.
		  The most challenging component of our competition is computer vision based localization.
		  We detect lines and ground robots using input from five on-board RGBD cameras using our customized detection algorithms.
		  The results are passed onto a highly sophisticated model that fuses input from the on-board inertial measurement unit (IMU) and computer vision results to predict the location of our vehicle in real time.
		  We also benchmark various state-of-the-art object tracking algorithms and adapt the one best suited for our mission.
		  Finally, we execute a mission strategy using knowledge of our current state of the vehicle and ground robots inside the competition arena.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
	<div class="p-5">
	  <%= image_tag "about/1iarc.jpeg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6">
	<div class="p-5">
	  <h2 class="display-4">The Infrastructure of Intelligent Flight</h2>
	  <p>The Software Infrastructure team writes the software that coordinates the execution of navigation software, simulates the competition, and communicates with the physical hardware. We allow various navigation software components to communicate with each other. In addition, we write software which provides a publish/subscribe interface to the physical hardware, allowing navigation software components to subscribe to sensor updates or publish control input. To simulate the competition, we can swap out the hardware interface software with simulator software that exposes the same interface to the navigation software components, but instead of talking to hardware, talks to a simulated quadcopter in a simulated field. The Software Infrastructure team writes both embedded, bare metal software running on an ARM microcontroller, low level Linux Software, and Linux applications.</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "about/joinus.jpeg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">A Growing Team</h2>
	  <p>Software is one of MAAV's largest growing subteams. With added focus on a onboarding and training.
		  Software has restructured into one of the most productive groups on MAAV. Building the brain of the drone is hard work and we are always
	  looking for hard working students interested in learning more about the world of intelligent robotics  </p>
	</div>
      </div>
    </div>
  </div>
</section>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Michigan Autonomous Aerial Vehicles</p>
  </div>
  <!-- /.container -->
</footer>

app/views/pages/home.html.erb
<div class="slide story" id="slide-1" data-slide="1">
	<div class="container">
		<div id="home-row-1" class="row clearfix">
			<div class="col-12">
				<h1 class="font-thin">Welcome to
					<span class="font-semibold">
						MAAV</span></h1>
				<h4 class="font-thin">The
					<span class="font-semibold">University of Michigan's
					</span>
					premiere autonomous air vehicle organization</h4>
				<br>
				<br>
			</div>
			<!-- /col-12 -->
		</div>
		<!-- /row -->
	</div>
</div>

<div class="slide story" id="slide-2" data-slide="2">
	<div class="container">
		<div class="row title-row">
			<div class="col-12 font-thin">
				<span class="font-semibold">MAAV</span>
				is a fully student led project team at the University of Michigan that builds an autonomous drone to compete at the annual International Aerial Robotics Competition (IARC). Members of
				<span class="font-semibold">MAAV</span>
				engage in the designing, building, and testing of an autonomous unmanned aerial system (UAS) while furthering multiple areas of Computer Science and Aerospace Engineering research.</div>
		</div>
		<!-- /row -->
		<div class="row line-row">
			<div class="hr">&nbsp;</div>
		</div>
		<!-- /row -->
		<div class="row subtitle-row">
			<div class="col-12 font-thin">This is what
				<span class="font-semibold">we do</span></div>
		</div>
		<!-- /row -->
		<div class="row content-row">

			<div class="col-12 col-lg-3 col-sm-6">
				<p>
					<i class="icon icon-wrench"></i>
				</p>
				<h2 class="font-thin">
					<span class="font-semibold">Structures</span></h2>
				<h4 class="font-thin">Our structures team is responsible for the design and fabrication of MAAV's airframes. Our quadcopter is a combination of carbon fiber, milled plastic, and 3D printed plastic, which creates a durable, light airframe that can
					withstand intense maneuvers and crashes.</h4>
			</div>
			<!-- /col12 -->
			<div class="col-12 col-lg-3 col-sm-6">
				<p>
					<i class="icon icon-laptop"></i>
				</p>
				<h2 class="font-thin">
					<span class="font-semibold">Software</span></h2>
				<h4 class="font-thin">Our software team develops and implements algorithms that enable the drone to fly on its own, and creates utilities, such as simulators, that are used by other subteams. We also write algorithms to process raw data collected from our sensors.</h4>
			</div>
			<!-- /col12 -->
			<div class="col-12 col-lg-3 col-sm-6">
				<p>
					<i class="icon icon-bolt"></i>
				</p>
				<h2 class="font-thin">
					<span class="font-semibold">Circuits
					</span>
				</h2>
				<h4 class="font-thin">Circuits designs and builds electrical hardware, for both the vehicle and for testing. The vehicle's printed circuit board (PCB) provides a platform for the control software to run and communicate with the navigation software,
					as well as manage the safety of the battery, motors, and operators.</h4>
			</div>
			<!-- /col12 -->
			<div class="col-12 col-lg-3 col-sm-6">
				<p>
					<i class="icon icon-dollar"></i>
				</p>
				<h2 class="font-semibold">Business</h2>
				<h4 class="font-thin">Our business team is responsible for outreach and management. We contact potential sponsors, create the annual budget for all the teams, and manage the organization to ensure all teams are working in unison to develop and improve the drone.</h4>
			</div>
			<!-- /col12 -->
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /slide2 -->

<div class="slide story" id="slide-5" data-slide="5">
	<div class="container">
		<div class="row title-row">
			<div class="col-12 font-thin">
				<span class="font-semibold">Our Sponsors:</div>
			</div>
			<!-- /row -->
			<div class="row line-row">
				<div class="hr">&nbsp;</div>
			</div>
			<!-- /row -->
			<div class="row subtitle-row">
				<div class="col-sm-1 hidden-sm">&nbsp;</div>
				<div class="col-12 col-sm-10 font-light">Our success in the development of the quadcopter is due in no small part to the support we receive from our sponsors.
				</div>
				<div class="col-sm-1 hidden-sm">&nbsp;</div>
			</div>
			<!-- /row -->
			<div class="row content-row">
				<div class="col-md-4"><%= image_tag "home/lockheedmart.png", rlass: "img-fluid" %></div>
				<div class="col-md-4"><%= image_tag "home/umich-engin.png", class: "img-fluid" %></div>
				<div class="col-md-4"><%= image_tag "home/northrop-grumman.png", class: "img-fluid" %></div>
			</div>
			<div class="row content-row">
				<div class="col-md-4"><%= image_tag "home/saleae.png", class: "img-fluid" %></div>
				<div class="col-md-4"><%= image_tag "home/3dr.png" %></div>
				<div class="col-md-4"><%= image_tag "home/dji.png" %></div>
			</div>
		</div>
		<!-- /container -->

	</div>

	<div class="slide story" id="slide-6" data-slide="6">
		<div class="container">
			<div class="row title-row">
				<div class="col-12 font-light">Get in<span class="font-semibold">
						touch</span></div>
			</div>
			<!-- /row -->
			<div class="row line-row">
				<div class="hr">&nbsp;</div>
			</div>
			<!-- /row -->
			<div class="row subtitle-row">
				<div class="col-sm-1 hidden-sm">&nbsp;</div>
				<div class="col-12 col-sm-10 font-light">Feel free to reach out, we would love to get to know you</div>
				<div class="col-sm-1 hidden-sm">&nbsp;</div>
			</div>
			<!-- /row -->
			<div id="contact-row-4" class="row">
				<div class="col-sm-1 hidden-sm">&nbsp;</div>
				<div class="col-12 col-sm-2 with-hover-text">
					<p>
						<a target="_top" href="mailto:maav-leads@umich.edu">
							<i class="fa fa-envelope fa-5x"></i>
						</a>
					</p>
					<span class="hover-text font-light ">maav-leads@umich.edu</span></a>
			</div>
			<!-- /col12 -->
			<div class="col-12 col-sm-2 with-hover-text">
				<p>
					<a target="_blank" href="http://teamprojects.engin.umich.edu/teams/michigan-autonomous-aerial-vehicles">
						<i class="fa fa-home fa-5x"></i>
					</a>
				</p>
				<span class="hover-text font-light ">Wilson Center<br>North Campus, University of Michigan</span></a>
		</div>
		<!-- /col12 -->
		<div class="col-12 col-sm-2 with-hover-text">
			<p>
				<a target="_blank" href="https://twitter.com/maavteam">
					<i class="fa fa-twitter fa-5x"></i>
				</a>
			</p>
			<span class="hover-text font-light ">@MAAVteam</span></a>
	</div>
	<!-- /col12 -->
	<div class="col-12 col-sm-2 with-hover-text">
		<p>
			<a target="_blank" href="https://medium.com/maav">
				<i class="fa fa-medium fa-5x"></i>
			</a>
		</p>
		<span class="hover-text font-light ">@MAAV</span></a>
</div>
<!-- /col12 -->
<div class="col-12 col-sm-2 with-hover-text">
	<p>
		<a target="_blank" href="https://www.facebook.com/MichiganAutonomousAerialVehiclesTeam/">
			<i class="fa fa-facebook fa-5x"></i>
		</a>
	</p>
	<span class="hover-text font-light ">@MichiganAutonomousArialVehiclesTeam</span></a>
</div>
<!-- /col12 -->
<div class="col-sm-1 hidden-sm">&nbsp;</div>
</div>
<!-- /row -->
</div>
<!-- /container -->
</div>

app/views/pages/structures.html.erb
<header class="masthead structures">
  <div class="overlay">
    <div class="container">
	    <br>
	    <br>
      <h1 class="display-1 text-white">Structures</h1>
      <br>
      <br>
    </div>
  </div>
</header>
<div id="structures-slide-2">
<section>
  <div class="container" >
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "structures/Picture1.png", class: "img-fluid rounded-circle", style: "height: 25rem;"%>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Building the Future</h2>
	  <p>The structures team handles the design and engineering of the vehicle.
	 Using solidworks, the structures continues to develop vehicle components throughout the semester.
 	 Through continuous design review and experimentation, the team determines the best design strategies for the vehicle.
 	Currently the vehicle is built out of a mix of carbon fiber, metal components and 3D printed parts</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
	<div class="p-5">
	  <%= image_tag "structures/structures_team.jpg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6">
	<div class="p-5">
	  <h2 class="display-4">Flight Ready</h2>
	  <p>The structures team spends a lot of time preparing the vehicle for continuous flight testing.
	Testing at MAAV's hangar at Ann Arbor's Willow Run Airport, the structures team works hard to carefully evaluate the
	drone's aerodynamic capabilities and make sure our drone is flying as smoothly as possible.
	</p>
	</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-2">
	<div class="p-5">
	  <%= image_tag "about/joinus.jpeg", class: "img-fluid rounded-circle" %>
	</div>
      </div>
      <div class="col-md-6 order-1">
	<div class="p-5">
	  <h2 class="display-4">Agile</h2>
	  <p>One of the smallest teams on MAAV, the structures team works hard and revises often. Comprised of Aerospace and Mechanical Engineering
	  students, the team collaborates with everyone from the software navigation team to the aerospace department to make sure that our design is
  ready to go when we take the field at IARC </p>
	</div>
      </div>
    </div>
  </div>
</section>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Michigan Autonomous Aerial Vehicles</p>
  </div>
  <!-- /.container -->
</footer>